### ISSUE TITLE
Error when running annotate.py

### ISSUE THREAD

**Issue by hoyaka** [Mrqeoqqt/chemdistiller#5]
Hi developer, 

I was trying to run a test run using annotate.py, but all I got was an error message as the following:  

```
Traceback (most recent call last):

  File "/Users/.../chemdistiller/annotate.py", line 597, in <module>
    run_annotation(args.input_spectra_folder, db_file, chemical_databases, args.output_folder, SVMs_path, ncpu, ppm, max_results_per_query, True);

  File "/Users/.../chemdistiller/annotate.py", line 333, in run_annotation
    for index in range(len(annotation.mol_candidates.mol_list)):

AttributeError: 'NoneType' object has no attribute 'mol_list'
```

Do you know what the problem is here and how to fix this? 

Regards, 
Katharine C

**Comment by Mrqeoqqt** [comment]
Hi Katharine,

Thanks for notice. I guess it is caused by `DBs/` and `SVMs/` folders, which are not uploaded to this repo.

To run chemdistiller successfully, you have to **download `DBs/` and `SVMs/` in advance**. A core version `DBs/` can be downloaded from _https://bitbucket.org/iAnalytica/chemdistillerpython/src/master/DBs/_. Besides, I downloaded Linear Weighted SVM from https://www.mediafire.com/folder/v4lb8s2nns9c6/SVMs, extracted and renamed it to `SVMs`. After that, I ran `python annotate.py --test` in both command line and VSCode debug mode. Both terminated normally and gave desired outputs.

The main logic of chemdistiller is the `run_annotation` function in `annotate.py`. Its workflow is as follows,
- use `SpectralManager` to read and manage all test files under `data/MassBankTestSpectra` folder
- generate a `MSSpectrum` instance for each test file, and each `MSSpectrum` instance managers nested `MSPeakAnnotation` instances
- use `PeakAnnotator` to compare peaks to test with those in database

FYI, the original chemdistiller project is located at _https://bitbucket.org/iAnalytica/chemdistillerpython/src/master/_, developed by Dr. Ivan Laponogov and his group. I didn't touch the rest of this project except for the indexing (or numbering) in the html output. My major work focused on writing file parsers for this project. 

Hope you find this reply helpful.

Best,
Mingyi

**Comment by hoyaka** [comment]
Hi Mingyi, 

Thank you so much for your information. I did download the `DBs` and `SVMs` and stored them in the designated folders. The error resulted is based on everything are in their right place. I also downloaded the original source code from bitbucket and tried to run the `annotate.py` using Spyder with `DBs` and `SVMs` folders, but I got the same error message. I asked a post-grad in my lab to run both the code packages on here and on bitbucket, and he got the same error message as the one I mentioned as well. He told me that the `mol_candidates` is set as None inside the `MSPeakAnnotation` function, which is the function we believe initiates the `annotation` in `annotate.py`. 

![image](https://user-images.githubusercontent.com/75922180/127878273-2f5b122d-8d54-4a7b-a9c4-c516ffadfa85.png)

Did you alternate anything in the code except the `DBs` and `SVMs`? Are you able to provide me the code package you are able to successfully run with? 

I tried to get in touch with Dr. Reza Mirnezami and Dr. Kirill Veselkov through email, but sadly no one replied. If you are able to connect me with any of the authors, that will be very helpful too. 

Regards, 
Katharine C

**Comment by Mrqeoqqt** [comment]
Hi Katharine,

The `__init__` method in `class MSPeakAnnotation` is used to initialize the annotation object. In `annotate.py : Line 274` (or some line around), `peak_annotator` invokes the `annotate_peaks` method and assign information to annotation objects for each peak. After this step, the `mol_candidates` are supposed to have values. Especially in the test mode, you will see "Retrieving and scoring candidates..." printed in the command line if `annotate_peaks` method is correctly invoked.

The error message you shared seems too general for me so that I cannot locate precisely which step went wrong. Did the program give some intermediate command-line outputs? If not, I recommend to pick only **one** `txt` file under `data/MassBankTestSpectra`, for example remove the other files except for `1.txt`, set toggles at key functions/class methods, and use the debug mode to track the program. `chemdistiller` prints messages before&after important steps to make users to track more easily.

---

Sorry that I didn't find a proper way to share a whole runnable replica. But the partial command-line output (after removing personalised data such as username) can be found at [command-line-output.txt](https://github.com/Mrqeoqqt/chemdistiller/files/6922853/command-line-output.txt). 


Best,
Mingyi

**Comment by Mrqeoqqt** [comment]
The anaconda virtual environment configuration I used to run `chemdistiller` can be found at [environment.txt](https://github.com/Mrqeoqqt/chemdistiller/files/6922914/environment.txt). The uploaded file contains more python packages than the necessary to run `chemdistiller`, but it is sufficient. You can try to run `python annotate.py --test` in this environment.

To create the same environment, 
1. download the above file and change the extension from `.txt` to `.yml` (`.yml` format is not supported when uploading)
2. create a new anaconda environment by `conda env create --file environment.txt`
3. activate the environment `conda activate chemdistiller`

**Comment by hoyaka** [comment]
Hi Mingyi, 

I figured out what was the problem I addressed previously. I put the SVM model files in an additional folder which added an extra layer when the program reads the files. That's why the error message popped up. So thank you so much for providing your detailed analysis on this issue, they really helped me a lots. 

But here I encountered another problem. As stated in the readme document of ChemDistiller, there are `-1` and `1` folders for each SVM model. They are present in the linear model but I only have `-1` folder in the radial model. I tried to run the radial model with just the `-1` folder along but did not work. I tried to run the `-1` folder directly and of course, it did not work too. Were you able to find the `1` folder in the radial model package downloaded from their online database? Were you even able to extract the 12 zip files inside the radial_7zip package because I could not? Is unpacking those zip files necessary? 

Regards, 
Katharine Chau 

<img width="227" alt="Screen Shot 2021-08-23 at 9 33 03 AM" src="https://user-images.githubusercontent.com/75922180/130730908-6fb2afa0-3ee4-4f42-ae1d-10782331c703.png">

<img width="750" alt="Screen Shot 2021-08-23 at 9 33 27 AM" src="https://user-images.githubusercontent.com/75922180/130730920-4c9de96b-a3b5-4e1d-b4ea-abab0c5d7105.png">

<img width="758" alt="Screen Shot 2021-08-23 at 9 33 39 AM" src="https://user-images.githubusercontent.com/75922180/130730985-8ebe15bf-5cf1-47b3-8999-9af7148ee01f.png">

**Comment by Mrqeoqqt** [comment]
Sorry that I didn't explore into that part.

**Comment by hoyaka** [comment]
So have you been using the linear SVM when running the test? 

-Katharine

**Comment by Mrqeoqqt** [comment]
Yes. I only tried the linear SVM dataset in testing, but I didn't look into how the model is trained and generated.

**Comment by hoyaka** [comment]
I see. Thank you so much for answering my questions. 

-Katharine
